// <auto-generated />
using System;
using DocumentProcessing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentProcessing.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DocumentProcessing.Core.Domain.Document", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<string>("TenantId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("FileName").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("BlobPath").IsRequired().HasMaxLength(1024).HasColumnType("nvarchar(1024)");
            b.Property<string>("Checksum").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<long>("FileSizeBytes").HasColumnType("bigint");
            b.Property<int?>("PageCount").HasColumnType("int");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("FailureReason").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("FailureMessage").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("UpdatedAt").IsConcurrencyToken().HasColumnType("datetimeoffset");
            b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRowVersion().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.HasIndex("TenantId", "Status");
            b.HasIndex("CreatedAt");
            b.ToTable("Documents");
        });

        modelBuilder.Entity("DocumentProcessing.Core.Domain.DocumentPage", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<Guid>("DocumentId").HasColumnType("uniqueidentifier");
            b.Property<int>("PageNumber").HasColumnType("int");
            b.Property<string>("ExtractedText").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("DocumentId", "PageNumber").IsUnique();
            b.ToTable("DocumentPages");
        });

        modelBuilder.Entity("DocumentProcessing.Core.Domain.AuditEntry", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<Guid>("DocumentId").HasColumnType("uniqueidentifier");
            b.Property<string>("FromStatus").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("ToStatus").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
            b.Property<string>("Message").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
            b.Property<string>("Actor").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("DocumentId");
            b.HasIndex("OccurredAt");
            b.ToTable("AuditEntries");
        });

        modelBuilder.Entity("DocumentProcessing.Core.Domain.DocumentPage", b =>
        {
            b.HasOne("DocumentProcessing.Core.Domain.Document", null)
                .WithMany("Pages")
                .HasForeignKey("DocumentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("DocumentProcessing.Core.Domain.AuditEntry", b =>
        {
            b.HasOne("DocumentProcessing.Core.Domain.Document", null)
                .WithMany("AuditEntries")
                .HasForeignKey("DocumentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
